import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {spawnSync}from'node:child_process';
import {minimal,temporary,root}from'./helpers.mjs';
import {startPreview}from'../src/server.mjs';
const cli=path.join(root,'bin/estrato.mjs');const run=(...args)=>spawnSync(process.execPath,[cli,...args],{encoding:'utf8',timeout:15000});
test('CLI --version',()=>{const r=run('--version');assert.equal(r.status,0);assert.equal(r.stdout.trim(),'0.1.0');});
test('CLI --help',()=>{const r=run('--help');assert.equal(r.status,0);assert(r.stdout.includes('estrato scan'));});
test('unknown flags return machine-readable failures',()=>{const r=run('build','missing.json','--invented','--json');assert.equal(r.status,2);assert.equal(JSON.parse(r.stdout).ok,false);});
test('init refuses accidental overwrite',t=>{const dir=temporary(t),file=path.join(dir,'project.json');assert.equal(run('init',file).status,0);assert.equal(run('init',file).status,2);assert.equal(run('init',file,'--force').status,0);});
test('CLI build and check end-to-end',t=>{const dir=temporary(t),file=path.join(dir,'project.json'),out=path.join(dir,'docs');fs.writeFileSync(file,JSON.stringify(minimal()));const r=run('build',file,'--out',out,'--json');assert.equal(r.status,0,r.stderr+r.stdout);assert.equal(JSON.parse(r.stdout).ok,true);assert.equal(run('check',out,'--json').status,0);});
test('doctor finds the bundled renderer and skill',()=>{const r=run('doctor','--json');assert.equal(JSON.parse(r.stdout).ok,true);});
test('skill installer writes only the selected project',t=>{const dir=temporary(t);const r=run('skill','install','--agent','codex','--project',dir,'--json');assert.equal(r.status,0,r.stdout);assert(fs.existsSync(path.join(dir,'.agents/skills/estrato/SKILL.md')));assert.equal(run('skill','install','--project',dir).status,2);});
test('invalid options fail closed per command',()=>{assert.equal(run('doctor','--out','x','--json').status,2);assert.equal(run('serve','x','--port','NaN','--json').status,2);});
test('preview only serves the selected document and rejects alien hosts',async t=>{const dir=temporary(t),file=path.join(dir,'project.json');fs.writeFileSync(file,JSON.stringify(minimal()));const p=await startPreview(file);t.after(()=>p.close());const r=await fetch(p.url);assert.equal(r.status,200);assert((await r.text()).includes("connect-src 'self'"));assert.equal((await fetch(p.url+'/../secret')).status,404);assert.equal((await fetch(p.url,{method:'POST'})).status,405);const hostile=await new Promise((resolve,reject)=>{const request=http.get(p.url,{headers:{Host:'external.example'}},response=>{response.resume();resolve(response.statusCode);});request.on('error',reject);});assert.equal(hostile,403);});
test('live preview keeps last good revision after malformed JSON and reloads repaired input',async t=>{const dir=temporary(t),file=path.join(dir,'project.json');fs.writeFileSync(file,JSON.stringify(minimal()));const p=await startPreview(file);t.after(()=>p.close());const old=await (await fetch(p.url+'/__revision')).json();fs.writeFileSync(file,'{broken');await new Promise(r=>setTimeout(r,800));const bad=await (await fetch(p.url+'/__revision')).json();assert.equal(bad.revision,old.revision);assert(bad.error);const fixed=minimal();fixed.project.name='Repaired';fs.writeFileSync(file,JSON.stringify(fixed));await new Promise(r=>setTimeout(r,800));const good=await (await fetch(p.url+'/__revision')).json();assert.notEqual(good.revision,old.revision);assert.equal(good.error,null);});
