(() => {
  'use strict';
  const DATA=JSON.parse(document.getElementById('document-data').textContent),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const status={observed:'Observado no código',inferred:'Inferência a confirmar',proposed:'Proposta'};
  let index=0,tab='maps',zoom=1,selected=null,step=-1,tableMode=false,returnFocus=null,toastTimer;
  let theme=DATA.project.theme||'paper';
  try{const saved=localStorage.getItem('architecture-reader-theme');if(['paper','limestone','graphite'].includes(saved))theme=saved;}catch{}
  const map=()=>DATA.maps[index];
  function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
  function applyTheme(){document.body.dataset.theme=theme;$$('.app .diagram').forEach(svg=>svg.dataset.theme=theme);$('#theme-toggle').title='Tema: '+theme;try{localStorage.setItem('architecture-reader-theme',theme);}catch{}}
  function updateHash(id){try{history.replaceState(null,'','#map='+encodeURIComponent(map().id)+(id?'&node='+encodeURIComponent(id):''));}catch{}}
  function nav(){const query=$('#search').value.trim().toLocaleLowerCase('pt-BR');let html='',section='';
    if(!query&&tab==='guide'){html='<div class="nav-section">Guia do projeto</div>'+(DATA.guide||[]).map(g=>`<button class="guide-toc-link" data-chapter="${E(g.id)}">${E(g.title)}</button>`).join('');}
    else if(!query&&tab==='evidence'){html='<div class="nav-section">Referências de código</div>'+(DATA.evidence||[]).map(e=>`<button class="nav-item" data-evidence="${E(e.id)}"><span class="nav-number">${E(e.id)}</span><span>${E(e.title)}</span></button>`).join('');}
    else{if(query)html='<div class="search-summary">Mapas e componentes encontrados</div>';DATA.maps.forEach((m,i)=>{const hits=m.nodes.filter(n=>(n.label+' '+(n.subtitle||'')+' '+(n.description||'')).toLocaleLowerCase('pt-BR').includes(query));const matches=(m.title+' '+m.summary+' '+m.section).toLocaleLowerCase('pt-BR').includes(query);if(query&&!matches&&!hits.length)return;if(!query&&section!==(m.section||'Mapas')){section=m.section||'Mapas';html+=`<div class="nav-section">${E(section)}</div>`;}html+=`<button class="nav-item ${i===index&&tab==='maps'?'active':''}" data-map-index="${i}"${i===index&&tab==='maps'?' aria-current="page"':''}><span class="nav-number">${String(i+1).padStart(2,'0')}</span><span>${E(m.title)}</span></button>`;if(query)html+=hits.slice(0,6).map(n=>`<button class="nav-item search-hit" data-map-index="${i}" data-focus="${E(n.id)}">↳ ${E(n.label)}</button>`).join('');});if(query&&!html.includes('data-map-index'))html+='<div class="empty">Nenhum resultado.</div>';}
    $('#navigation').innerHTML=html;
  }
  function chips(ids){return [...new Set(ids)].map(id=>`<button class="evidence-chip" data-evidence="${E(id)}">${E(id)}</button>`).join('');}
  function footer(){return `<footer class="content-footer"><span>${E(DATA.project.scope||'As relações representam o que foi documentado, não observação de tráfego em produção.')}</span><span>Documento offline · ${DATA.maps.length} mapas</span></footer>`;}
  function showMap(i,focus){index=Math.max(0,Math.min(DATA.maps.length-1,i));tab='maps';zoom=1;selected=null;step=-1;closeInspector(false);render();updateHash(focus);if(focus)inspect(focus);}
  function render(){
    $$('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-selected',String(b.dataset.tab===tab));});
    if(tab==='maps')renderMap();else if(tab==='guide')$('#content').innerHTML=DATA.guideHtml+footer();else if(tab==='evidence')$('#content').innerHTML=DATA.evidenceHtml+footer();else $('#content').innerHTML=DATA.reviewHtml+footer();nav();applyTheme();
  }
  function renderMap(){const m=map(),refs=m.nodes.flatMap(n=>n.evidence||[]).concat(m.edges.flatMap(e=>e.evidence||[]));
    $('#content').innerHTML=`<div class="map-heading"><div><div class="eyebrow">${E(m.section||'Arquitetura')} / ${String(index+1).padStart(2,'0')} de ${String(DATA.maps.length).padStart(2,'0')}</div><h1>${E(m.title)}</h1><p class="lead">${E(m.summary||'')}</p></div><div class="pager"><button class="icon-btn" data-action="previous" aria-label="Mapa anterior" ${index===0?'disabled':''}>←</button><span>${index+1} / ${DATA.maps.length}</span><button class="icon-btn" data-action="next" aria-label="Próximo mapa" ${index===DATA.maps.length-1?'disabled':''}>→</button></div></div>
      ${(m.steps||[]).length?`<div class="steps" aria-label="Leitura guiada">${m.steps.map((s,i)=>`<button class="step ${step===i?'active':''}" data-step="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span><span><strong>${E(s.title)}</strong>${E(s.description||'')}</span></button>`).join('')}</div>`:''}
      <section class="map-panel" aria-label="Diagrama interativo"><div class="toolbar"><span class="toolbar-label">${tableMode?'Componentes e relações':'Selecione um componente para explorar'}</span><div class="toolbar-actions"><button class="icon-btn" data-action="zoom-out" aria-label="Reduzir zoom">−</button><button class="icon-btn" data-action="fit">Ajustar</button><button class="icon-btn" data-action="zoom-in" aria-label="Aumentar zoom">+</button><span class="divider"></span><button class="icon-btn" data-action="table">${tableMode?'Diagrama':'Tabela'}</button><button class="icon-btn" data-action="expand">Ampliar</button><details class="export"><summary class="icon-btn">Exportar ↓</summary><div class="export-popover"><button data-export="svg">Diagrama SVG</button><button data-export="png">Imagem PNG</button><button data-export="json">Fonte JSON completa</button><button data-export="markdown">Guia Markdown</button><button data-export="print">Imprimir documento</button></div></details></div></div>
      ${tableMode?renderTable(m):`<div class="viewport" tabindex="0" aria-label="Área do diagrama, com rolagem e zoom"><div class="canvas">${m.svg}</div></div>`}
      <div class="map-legend"><span class="legend-items"><span><i class="legend-sample"></i>Relação</span><span><i class="legend-sample warm"></i>Destaque</span><span><i class="legend-sample dashed"></i>Condicional</span></span><span class="legend-note">${m.type==='sequence'?'Mensagens em ordem de declaração':'Relações documentadas · sem inferência de tráfego'}</span></div></section>
      ${(m.notes||[]).length?`<div class="map-notes">${m.notes.map(n=>`<article class="note"><h3>${E(n.title)}</h3><p>${E(n.text).replace(/\n/g,'<br>')}</p></article>`).join('')}</div>`:''}
      ${refs.length?`<div class="evidence-strip"><span>Fontes desta vista</span>${chips(refs)}</div>`:''}${footer()}`;
    requestAnimationFrame(fit);
  }
  function renderTable(m){return `<div class="table-view"><div class="table-scroll"><table class="node-table"><thead><tr><th>Componente</th><th>Responsabilidade</th><th>Evidência</th></tr></thead><tbody>${m.nodes.map(n=>`<tr><td><button class="btn" data-inspect="${E(n.id)}">${E(n.label)}</button></td><td>${E(n.description||n.subtitle||'Não descrita.')}</td><td>${chips(n.evidence||[])}</td></tr>`).join('')}</tbody></table></div><h3>Relações documentadas</h3><div class="table-scroll"><table><thead><tr><th>Origem</th><th>Destino</th><th>Relação</th></tr></thead><tbody>${m.edges.map(e=>`<tr><td>${E(m.nodes.find(n=>n.id===e.from)?.label)}</td><td>${E(m.nodes.find(n=>n.id===e.to)?.label)}</td><td>${E(e.label||'')}</td></tr>`).join('')}</tbody></table></div></div>`;}
  function fit(){const svg=$('.canvas .diagram'),viewport=$('.viewport');if(!svg||!viewport)return;const width=Math.max(viewport.clientWidth,window.innerWidth<780?map().width*.72:0);svg.style.width=(width*zoom)+'px';svg.style.height='auto';$('.canvas').style.width=Math.max(width*zoom,viewport.clientWidth)+'px';}
  function highlight(nodes=[],edges=[]){const ns=new Set(nodes),es=new Set(edges),active=nodes.length||edges.length;$$('.canvas [data-node]').forEach(el=>{el.classList.toggle('selected',ns.has(el.dataset.node));el.classList.toggle('dimmed',!!active&&!ns.has(el.dataset.node));});$$('.canvas [data-edge]').forEach(el=>{el.classList.toggle('selected',es.has(el.dataset.edge));el.classList.toggle('dimmed',!!active&&!es.has(el.dataset.edge));});}
  function inspect(id){const m=map(),n=m.nodes.find(n=>n.id===id);if(!n)return;selected=id;returnFocus=document.activeElement;highlight([id],m.edges.filter(e=>e.from===id||e.to===id).map(e=>e.id));
    const connections=m.edges.filter(e=>e.from===id||e.to===id);
    $('#inspector').innerHTML=`<header><span>Detalhes do componente</span><button class="icon-btn" data-action="close-inspector" aria-label="Fechar detalhes">×</button></header><div class="eyebrow">${E(n.kind||'Componente')}</div><h2 id="inspector-title">${E(n.label)}</h2><p class="lead">${E(n.subtitle||n.technology||'')}</p>${n.status?`<p style="margin-top:15px"><span class="pill">${E(status[n.status]||n.status)}</span></p>`:''}<h3>Responsabilidade</h3><p class="description">${E(n.description||'Responsabilidade ainda não descrita.')}</p>${n.owner?`<p class="description">Responsável: ${E(n.owner)}</p>`:''}<h3>Explorar relações</h3><div class="actions"><button class="btn" data-reach="upstream">Origens</button><button class="btn" data-reach="downstream">Destinos</button><button class="btn" data-action="clear-focus">Limpar foco</button></div><p class="help-text">O alcance considera apenas as setas desta vista. Não representa impacto em produção.</p><h3>Traçar rota até</h3><select id="route-target" aria-label="Componente de destino">${m.nodes.filter(x=>x.id!==id).map(x=>`<option value="${E(x.id)}">${E(x.label)}</option>`).join('')}</select><button class="btn" data-action="route">Mostrar caminho dirigido</button><h3>Relações diretas · ${connections.length}</h3>${connections.map(e=>`<div class="rel"><strong>${E(m.nodes.find(x=>x.id===e.from)?.label)}</strong> → <strong>${E(m.nodes.find(x=>x.id===e.to)?.label)}</strong><br>${E(e.label||'Relação sem rótulo')}${e.description?'<br>'+E(e.description):''}</div>`).join('')}<h3>Referências</h3><div class="evidence-strip">${n.evidence?.length?chips(n.evidence):'<span>Sem referência vinculada.</span>'}</div>`;
    $('#inspector').hidden=false;$('#overlay').hidden=false;$('#inspector').querySelector('button').focus();updateHash(id);
  }
  function closeInspector(restore=true){$('#inspector').hidden=true;$('#overlay').hidden=true;if(restore&&returnFocus?.isConnected)returnFocus.focus();}
  function reach(direction){const ns=new Set([selected]),es=new Set(),queue=[selected];while(queue.length){const current=queue.shift();for(const e of map().edges){const from=direction==='upstream'?e.to:e.from,to=direction==='upstream'?e.from:e.to;if(from===current){es.add(e.id);if(!ns.has(to)){ns.add(to);queue.push(to);}}}}highlight([...ns],[...es]);closeInspector();toast(`${ns.size} componentes alcançáveis nas relações documentadas.`);}
  function trace(){const target=$('#route-target')?.value,previous=new Map([[selected,null]]),queue=[selected];while(queue.length){const current=queue.shift();if(current===target)break;for(const e of map().edges)if(e.from===current&&!previous.has(e.to)){previous.set(e.to,{node:current,edge:e.id});queue.push(e.to);}}if(!previous.has(target)){toast('Não há caminho dirigido documentado entre os componentes.');return;}const ns=[],es=[];for(let id=target;id;){ns.push(id);const p=previous.get(id);if(!p)break;es.push(p.edge);id=p.node;}highlight(ns,es);closeInspector();toast(`${es.length} relações no caminho documentado.`);}
  function showEvidence(id){closeInspector(false);tab='evidence';render();const el=$(`#reference-${CSS.escape(id)}`);if(el){el.classList.add('highlight');el.scrollIntoView({behavior:'smooth',block:'start'});}}
  function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  function cleanSvg(){const wrapper=document.createElement('div');wrapper.innerHTML=map().svg;const svg=wrapper.firstElementChild;svg.dataset.theme=theme;svg.setAttribute('width',String(map().width));svg.setAttribute('height',String(map().height));return new XMLSerializer().serializeToString(svg);}
  async function exportFile(type){$$('.export').forEach(d=>d.open=false);const filename=map().id;
    if(type==='svg')saveBlob(new Blob([cleanSvg()],{type:'image/svg+xml;charset=utf-8'}),filename+'.svg');
    else if(type==='json')saveBlob(new Blob([JSON.stringify(DATA.source,null,2)+'\n'],{type:'application/json'}),'architecture.json');
    else if(type==='markdown')saveBlob(new Blob([DATA.guideMarkdown],{type:'text/markdown;charset=utf-8'}),'guia.md');
    else if(type==='print')window.print();
    else if(type==='png'){const svg=cleanSvg(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml;charset=utf-8'}));try{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('Falha ao converter o SVG.'));image.src=url;});const ratio=Math.min(2,4096/Math.max(map().width,map().height)),canvas=document.createElement('canvas');canvas.width=Math.ceil(map().width*ratio);canvas.height=Math.ceil(map().height*ratio);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas não disponível.');ctx.drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('PNG não disponível neste navegador.');saveBlob(blob,filename+'.png');}catch(error){toast(error.message);}finally{URL.revokeObjectURL(url);}}
  }
  const actions={previous:()=>showMap(index-1),next:()=>showMap(index+1),'zoom-in':()=>{zoom=Math.min(3,zoom+.2);fit();},'zoom-out':()=>{zoom=Math.max(.4,zoom-.2);fit();},fit:()=>{zoom=1;fit();highlight();},table:()=>{tableMode=!tableMode;renderMap();applyTheme();},expand:async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('.map-panel').requestFullscreen();fit();}catch{toast('Tela cheia indisponível neste navegador. Use os controles de zoom.');}},'close-inspector':()=>closeInspector(),'clear-focus':()=>{selected=null;highlight();closeInspector();updateHash();},route:trace};
  document.addEventListener('click',event=>{const target=event.target.closest('button, [data-node]');if(target){if(target.dataset.tab){tab=target.dataset.tab;closeInspector(false);render();return;}if(target.dataset.mapIndex!==undefined){showMap(Number(target.dataset.mapIndex),target.dataset.focus);$('#sidebar').classList.remove('open');return;}if(target.dataset.chapter){tab='guide';render();document.getElementById('chapter-'+target.dataset.chapter)?.scrollIntoView({block:'start'});$('#sidebar').classList.remove('open');return;}if(target.dataset.evidence){showEvidence(target.dataset.evidence);$('#sidebar').classList.remove('open');return;}if(target.dataset.node||target.dataset.inspect){inspect(target.dataset.node||target.dataset.inspect);return;}if(target.dataset.reach){reach(target.dataset.reach);return;}if(target.dataset.action){actions[target.dataset.action]?.();return;}if(target.dataset.export){exportFile(target.dataset.export);return;}if(target.dataset.step!==undefined){step=Number(target.dataset.step);const s=map().steps[step];$$('.step').forEach((el,i)=>el.classList.toggle('active',i===step));highlight(s.nodes||[],s.edges||[]);if(!(s.nodes?.length||s.edges?.length))toast(s.description||s.title);return;}}
    if(event.target===$('#overlay'))closeInspector();
  });
  $('#search').addEventListener('input',nav);$('#theme-toggle').addEventListener('click',()=>{theme=['paper','limestone','graphite'][(['paper','limestone','graphite'].indexOf(theme)+1)%3];applyTheme();});$('#menu-toggle').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open));if(open)$('#search').focus();});
  document.addEventListener('keydown',event=>{
    const input=/INPUT|TEXTAREA|SELECT/.test(event.target.tagName);if(event.key==='Escape'){$('#sidebar').classList.remove('open');closeInspector();$$('.export').forEach(d=>d.open=false);return;}
    if(!$('#inspector').hidden&&event.key==='Tab'){const focusable=[...$('#inspector').querySelectorAll('button,select,a,input')],first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}return;}
    if(input||event.ctrlKey||event.metaKey||event.altKey)return;
    if(event.key==='Enter'&&event.target.dataset.node){inspect(event.target.dataset.node);event.preventDefault();return;}
    if(event.key==='/'){event.preventDefault();$('#sidebar').classList.add('open');$('#search').focus();}
    else if(event.key==='t')$('#theme-toggle').click();
    else if(tab==='maps'&&$('#inspector').hidden){if(event.key==='+')actions['zoom-in']();if(event.key==='-')actions['zoom-out']();if(event.key==='0')actions.fit();if(event.key==='ArrowRight')actions.next();if(event.key==='ArrowLeft')actions.previous();}
  });
  window.addEventListener('resize',fit);document.addEventListener('fullscreenchange',fit);
  const hash=new URLSearchParams(location.hash.slice(1)),start=DATA.maps.findIndex(m=>m.id===hash.get('map'));if(start>=0)index=start;render();if(hash.get('node'))inspect(hash.get('node'));
})();
