import fs from 'node:fs';
import {escapeHtml as e,safeJson} from './io.mjs';
import {themeCSS} from './themes.mjs';
import {markdown,guideMarkdown} from './markdown.mjs';
const css=fs.readFileSync(new URL('./viewer/style.css',import.meta.url),'utf8');
const runtime=fs.readFileSync(new URL('./viewer/runtime.js',import.meta.url),'utf8');
function evidenceHtml(p){return `<header class="document-header"><div class="eyebrow">Rastreabilidade</div><h1>Evidências no código</h1><p class="lead">Origens, intervalos de linhas e versões documentadas. A existência de uma referência não certifica o funcionamento em produção.</p></header>${(p.evidence||[]).map(ev=>`<article class="ev-card" id="reference-${e(ev.id)}"><h2><span class="pill">${e(ev.id)}</span> ${e(ev.title)}</h2>${ev.note?`<p class="lead">${e(ev.note)}</p>`:''}${ev.references.map(r=>`<div style="margin-top:16px"><div class="origin">${e(r.path)}<br>Linhas ${r.start}–${r.end}</div>${r.sha256?`<div class="hash">SHA-256 ${e(r.sha256)}</div>`:'<div class="hash">Versão não fixada por hash.</div>'}${r.excerpt?`<details><summary>Ver trecho documentado</summary><pre><code>${e(r.excerpt)}</code></pre></details>`:''}</div>`).join('')}</article>`).join('')||'<div class="empty">Nenhuma evidência vinculada. Revise o código e adicione referências.</div>'}`;}
function guideHtml(p){return `<header class="document-header"><div class="eyebrow">Documentação técnica</div><h1>Guia do projeto</h1><p class="lead">${e(p.project.description||'Como o sistema está organizado e como seus processos funcionam.')}</p></header>${(p.guide||[]).map(g=>`<section class="document-section" id="chapter-${e(g.id)}"><h2>${e(g.title)}</h2><div class="prose">${markdown(g.body)}</div></section>`).join('')||'<div class="empty">Nenhum capítulo autoral foi incluído.</div>'}`;}
function reviewHtml(p){const entries=(list)=>list.map(f=>`<article class="finding"><span class="pill ${e(f.severity||'info')}">${e(f.severity||'info')}</span>${f.status?` <span class="pill">${e({observed:'Observado',inferred:'Inferência',proposed:'Proposta'}[f.status]||f.status)}</span>`:''}<h3>${e(f.title)}</h3><p>${e(f.description)}</p><div class="evidence-strip">${(f.evidence||[]).map(id=>`<button class="evidence-chip" data-evidence="${e(id)}">${e(id)}</button>`).join('')}</div></article>`).join('');return `<header class="document-header"><div class="eyebrow">Decisões e pontos de atenção</div><h1>Revisão da arquitetura</h1><p class="lead">Achados, hipóteses e decisões autorais, separados de validações automáticas.</p></header><h2>Pontos de atenção</h2>${entries(p.findings||[])||'<p class="empty">Nenhum achado foi registrado. Isso não significa ausência de problemas.</p>'}<h2 style="margin-top:35px">Decisões</h2>${entries(p.decisions||[])||'<p class="empty">Nenhuma decisão foi registrada.</p>'}`;}
export function renderHtml(project,rendered){
  const data={...project,source:project,maps:rendered,guideHtml:guideHtml(project),evidenceHtml:evidenceHtml(project),reviewHtml:reviewHtml(project),guideMarkdown:guideMarkdown(project)};
  const print=rendered.map((m,i)=>`<section class="print-page"><div class="eyebrow">${e(project.project.name)} · ${i+1} / ${rendered.length}</div><h1>${e(m.title)}</h1><p>${e(m.summary||'')}</p>${m.svg.replace('data-theme="'+(project.project.theme||'paper')+'"','data-theme="paper"')}<div>${(m.notes||[]).map(n=>`<h3>${e(n.title)}</h3><p>${e(n.text)}</p>`).join('')}</div></section>`).join('');
  return `<!doctype html>\n<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src blob: data:; font-src 'none'; connect-src 'none'; base-uri 'none'; form-action 'none'; object-src 'none'"><meta name="description" content="${e(project.project.description||'Arquitetura e funcionamento do sistema')}"><title>${e(project.project.name)} · Arquitetura</title><style>${themeCSS}\n${css}</style></head><body data-theme="${e(project.project.theme||'paper')}"><a class="skip" href="#content">Ir para o conteúdo</a><aside class="sidebar" id="sidebar"><div class="identity"><div class="project-wordmark">${e(project.project.name)}</div><small>Arquitetura do sistema</small></div><label class="search-box"><input id="search" type="search" placeholder="Buscar mapa ou componente" aria-label="Buscar mapa ou componente"><kbd>/</kbd></label><nav class="nav" id="navigation" aria-label="Navegação da documentação"></nav><footer class="side-footer"><strong>${project.maps.length} mapas · ${(project.evidence||[]).length} referências</strong><br>${e(project.project.snapshot||'Documentação do projeto')}</footer></aside><div class="app"><header class="topbar"><button class="icon-btn menu-toggle" id="menu-toggle" aria-label="Abrir navegação" aria-expanded="false" aria-controls="sidebar">☰</button><div class="tabs" role="tablist" aria-label="Seções da documentação"><button class="tab active" role="tab" data-tab="maps" aria-selected="true">Mapas</button><button class="tab" role="tab" data-tab="guide" aria-selected="false">Guia do projeto</button><button class="tab" role="tab" data-tab="evidence" aria-selected="false">Evidências</button><button class="tab" role="tab" data-tab="review" aria-selected="false">Revisão</button></div><div class="top-actions"><span class="scope-label">Documentação de arquitetura</span><span class="project-version">${e(project.project.version||'')}</span><button class="icon-btn" id="theme-toggle" aria-label="Alternar tema" title="Alternar tema">◐</button></div></header><main class="content" id="content" tabindex="-1"></main></div><div class="overlay" id="overlay" hidden></div><aside class="inspector" id="inspector" role="dialog" aria-modal="true" aria-labelledby="inspector-title" hidden></aside><div class="toast" id="toast" role="status" aria-live="polite" hidden></div><div class="print-document" data-theme="paper">${print}<section class="print-page">${data.guideHtml}</section><section class="print-page">${data.evidenceHtml}</section><section class="print-page">${data.reviewHtml}</section></div><script id="document-data" type="application/json">${safeJson(data)}</script><script>${runtime}</script></body></html>\n`;
}
