import {escapeHtml as esc} from './io.mjs';
import {themeCSS} from './themes.mjs';
const kindLabel={frontend:'INTERFACE',backend:'SERVIÇO',database:'DADOS',cloud:'EXTERNO',external:'ATOR EXTERNO',security:'CONTROLE',messagebus:'MENSAGERIA',worker:'WORKER',decision:'DECISÃO',state:'ESTADO',package:'PACOTE',module:'MÓDULO',file:'ARQUIVO'};
function wrap(text,length,max=2){const words=String(text||'').split(/\s+/),lines=[];let current='';for(let word of words){while(word.length>length){if(current){lines.push(current);current='';}lines.push(word.slice(0,length-1)+'·');word=word.slice(length-1);}if((current+' '+word).trim().length>length){lines.push(current);current=word;}else current=(current+' '+word).trim();}if(current)lines.push(current);if(lines.length>max){lines.length=max;lines[max-1]=lines[max-1].slice(0,length-1)+'…';}return lines;}
const tspans=(lines,x,y,size,height)=>lines.map((line,i)=>`<text x="${x}" y="${y+i*height}" font-size="${size}">${esc(line)}</text>`).join('');
export function renderSvg(map,graph,theme='paper'){
  const marker=`arrow-${map.id}`,clip=`clip-${map.id}`;
  const defs=`<defs><marker id="${marker}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 1 L 9 5 L 0 9" fill="none" stroke="context-stroke" stroke-width="1.5"/></marker></defs>`;
  const style=`${themeCSS}\nsvg{font-family:Arial,Helvetica,sans-serif;background:var(--panel);color:var(--ink)}text{fill:var(--ink)}.node-box{fill:var(--node);stroke:var(--line);stroke-width:1.2}.node{cursor:pointer;outline:none}.node:hover .node-box,.node:focus .node-box,.node.selected .node-box{stroke:var(--accent);stroke-width:2.5}.node.selected .node-box{fill:var(--soft)}.node.dimmed,.edge.dimmed{opacity:.13}.edge-path{stroke:var(--muted);stroke-width:1.5;fill:none;stroke-linejoin:round;stroke-linecap:round}.edge.emphasis .edge-path{stroke:var(--warm);stroke-width:2}.edge.conditional .edge-path{stroke-dasharray:6 5}.edge.selected .edge-path{stroke:var(--accent);stroke-width:3}.edge-label{fill:var(--panel)}.edge-label-text{fill:var(--muted);font-size:12px}.node-subtitle text{fill:var(--muted)}.kind-text{fill:var(--accent);font-size:9px;letter-spacing:1.2px}.node-label{font-weight:600}.evidence-mark{fill:var(--muted);font-size:9px}.boundary{fill:var(--soft);fill-opacity:.4;stroke:var(--line);stroke-dasharray:5 5}.boundary-label{font-size:10px;fill:var(--muted)}.lifeline{stroke:var(--line);stroke-width:1.5;stroke-dasharray:5 5}@media(prefers-reduced-motion:no-preference){.node,.edge{transition:opacity .18s ease}}`;
  const groups=graph.groups.map(g=>`<g><rect class="boundary" x="${g.x}" y="${g.y}" width="${g.w}" height="${g.h}" rx="8"/><text class="boundary-label" x="${g.x+12}" y="${g.y+17}">${esc(g.label)}</text></g>`).join('');
  const lifelines=graph.sequence?graph.nodes.map(n=>`<line class="lifeline" x1="${n.x+n.w/2}" x2="${n.x+n.w/2}" y1="${n.y+n.h}" y2="${graph.height-38}"/>`).join(''):'';
  const edges=graph.edges.map(e=>`<g class="edge ${esc(e.variant||'default')}" data-edge="${esc(e.id)}"><title>${esc(e.from)} → ${esc(e.to)}: ${esc(e.labelText)}</title><path class="edge-path" d="${e.points.map((p,i)=>(i?'L':'M')+p.join(' ')).join(' ')}" marker-end="url(#${marker})"/>${e.label?`<rect class="edge-label" x="${e.label.x-e.label.w/2}" y="${e.label.y-e.label.h/2}" width="${e.label.w}" height="${e.label.h}" rx="3"/>${(e.label.lines||[e.labelText||'']).map((line,i)=>`<text class="edge-label-text" text-anchor="middle" x="${e.label.x}" y="${e.label.y-((e.label.lines||[]).length-1)*7+i*14+3.7}">${esc(line)}</text>`).join('')}`:''}</g>`).join('');
  const nodes=graph.nodes.map(n=>{const labels=wrap(n.label,Math.floor((n.w-34)/10.4),2),subs=wrap(n.subtitle||n.technology||'',Math.floor((n.w-34)/7),2),x=n.x+18,labelY=n.y+53,subY=labelY+(labels.length-1)*22+24;const evidence=(n.evidence||[]).length;const radius=map.type==='lifecycle'?24:7;
    return `<g class="node" data-node="${esc(n.id)}" role="button" tabindex="0" aria-label="${esc(n.label)}. ${esc(n.subtitle)}. Abrir detalhes."><title>${esc(n.description||n.label)}</title><rect class="node-box" x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="${radius}"/><path d="M ${n.x+1} ${n.y+16} L ${n.x+1} ${n.y+n.h-16}" stroke="var(--accent)" stroke-width="2"/><text class="kind-text" x="${x}" y="${n.y+22}">${esc(kindLabel[n.kind]||String(n.kind||'COMPONENTE').toUpperCase())}</text><g class="node-label">${tspans(labels,x,labelY,20,22)}</g><g class="node-subtitle">${tspans(subs,x,subY,12.5,15)}</g>${evidence?`<text class="evidence-mark" x="${n.x+n.w-14}" y="${n.y+22}" text-anchor="end">${String(evidence).padStart(2,'0')} REF</text>`:''}</g>`;
  }).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" class="diagram" data-theme="${esc(theme)}" data-map="${esc(map.id)}" viewBox="0 0 ${graph.width} ${graph.height}" width="${graph.width}" height="${graph.height}" aria-label="${esc(map.title)}" role="group"><title>${esc(map.title)}</title><desc>${esc(map.summary||'Mapa de componentes e relações declaradas.')}</desc><style>${style}</style>${defs}<rect x="0" y="0" width="100%" height="100%" fill="var(--panel)"/>${groups}${lifelines}${edges}${nodes}</svg>`;
}
